name: filament
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.1 <3.0.0'

publish_to: none


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  ffigen: ^4.1.0

ffigen:
  output: 'lib/src/generated/native_gen.dart'
  headers:
    entry-points:
      - '../cpp/public/filament-dart.h'
  llvm-path:
    - '/Users/tym/RosettaLibs/llvm-13.0.0'